spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ssurkuouemreea-crs-@localhost:8761/eureka
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: '*'